#define isplus (token.attr == SYMBOL && token.value == PLUS)
#define isminus (token.attr == SYMBOL && token.value == MINUS)
#define istimes (token.attr == SYMBOL && token.value == TIMES)
#define isdiv (token.attr == RWORD && token.value == DIV)

#define isEql (token.attr == SYMBOL && token.value == EQL)
#define isNotEql (token.attr == SYMBOL && token.value == NOTEQL)
#define isGrtrThan (token.attr == SYMBOL && token.value == GRTRTHAN)
#define isLessThan (token.attr == SYMBOL && token.value == LESSTHAN)
#define isGrtrEql (token.attr == SYMBOL && token.value == GRTREQL)
#define isLessEql (token.attr == SYMBOL && token.value == LESSEQL)
